- name: Configure the agent
  template:
    src: "zabbix_agentd.conf.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"
  notify: Restart Zabbix-Agent

- name: Check agent status
  shell: "netstat -nlpt | grep 10050"
